-- Sample data for the Vibe Swiper app
-- Run this in your Supabase SQL Editor to populate the male_names table

INSERT INTO male_names (name, name_set, easy_pronunciation) VALUES
-- English Names
('Alexander', 'English', true),
('Benjamin', 'English', true),
('Christopher', 'English', false),
('Daniel', 'English', true),
('Ethan', 'English', true),
('Gabriel', 'English', true),
('Henry', 'English', true),
('Isaac', 'English', true),
('James', 'English', true),
('Liam', 'English', true),
('Matthew', 'English', true),
('Nathan', 'English', true),
('Oliver', 'English', true),
('Samuel', 'English', true),
('William', 'English', true),

-- Turkish Names
('Mehmet', 'Turkish', true),
('Ahmet', 'Turkish', true),
('Mustafa', 'Turkish', true),
('Ali', 'Turkish', true),
('Hasan', 'Turkish', true),
('Hüseyin', 'Turkish', true),
('İbrahim', 'Turkish', true),
('İsmail', 'Turkish', true),
('Ömer', 'Turkish', true),
('Osman', 'Turkish', true),
('Süleyman', 'Turkish', true),
('Yusuf', 'Turkish', true),
('Zeynel', 'Turkish', true),
('Emre', 'Turkish', true),
('Can', 'Turkish', true),

-- International Names
('Alejandro', 'International', true),
('Antonio', 'International', true),
('Carlos', 'International', true),
('Diego', 'International', true),
('Eduardo', 'International', true),
('Fernando', 'International', true),
('Giuseppe', 'International', true),
('Hassan', 'International', true),
('Ivan', 'International', true),
('Jean', 'International', true),
('Klaus', 'International', true),
('Lars', 'International', true),
('Miguel', 'International', true),
('Nikolai', 'International', true),
('Omar', 'International', true),
('Pierre', 'International', true),
('Rafael', 'International', true),
('Sebastian', 'International', true),
('Thomas', 'International', true),
('Viktor', 'International', true),
('Yuki', 'International', true),
('Zachary', 'International', true);
