-- Insert 75 names across all pools (mixed together)
INSERT INTO male_names (name, name_set, origin, meaning, easy_pronunciation, vibe_score) VALUES
-- ENGLISH NAMES (25 names)
('Liam', 'English', 'Irish', 'Strong-willed warrior', 'LEE-um', 0),
('Noah', 'English', 'Hebrew', 'Rest, comfort', 'NOH-ah', 0),
('Oliver', 'English', 'Latin', 'Olive tree', 'OH-li-ver', 0),
('Elijah', 'English', 'Hebrew', 'My God is the Lord', 'E-ly-jah', 0),
('William', 'English', 'Germanic', 'Resolute protector', 'WIL-yum', 0),
('James', 'English', 'Hebrew', 'Supplanter', 'Jaymz', 0),
('Benjamin', 'English', 'Hebrew', 'Son of the right hand', 'BEN-ja-min', 0),
('Lucas', 'English', 'Latin', 'Bringer of light', 'LOO-kas', 0),
('Henry', 'English', 'Germanic', 'Home ruler', 'HEN-ree', 0),
('Alexander', 'English', 'Greek', 'Defender of men', 'Al-ek-SAN-der', 0),
('Michael', 'English', 'Hebrew', 'Who is like God?', 'MY-kel', 0),
('Ethan', 'English', 'Hebrew', 'Strong, enduring', 'EE-than', 0),
('Daniel', 'English', 'Hebrew', 'God is my judge', 'DAN-yel', 0),
('Matthew', 'English', 'Hebrew', 'Gift of God', 'MATH-yoo', 0),
('Jacob', 'English', 'Hebrew', 'Supplanter', 'JAY-kob', 0),
('Logan', 'English', 'Scottish', 'Little hollow', 'LOH-gun', 0),
('Jackson', 'English', 'English', 'Son of Jack', 'JAK-son', 0),
('Aiden', 'English', 'Irish', 'Fiery one', 'AY-den', 0),
('Theodore', 'English', 'Greek', 'Gift of God', 'THEE-o-dohr', 0),
('Gabriel', 'English', 'Hebrew', 'God is my strength', 'GAY-bree-el', 0),
('Leo', 'English', 'Latin', 'Lion', 'LEE-oh', 0),
('Jaxon', 'English', 'English', 'Son of Jack (modern)', 'JAK-son', 0),
('Wyatt', 'English', 'English', 'Brave in war', 'WY-et', 0),
('Julian', 'English', 'Latin', 'Youthful', 'JOO-lee-an', 0),
('Evan', 'English', 'Welsh', 'The Lord is gracious', 'EH-van', 0),

-- TURKISH NAMES (25 names)
('Mehmet', 'Turkish', 'Turkish/Arabic', 'The praised one', 'MEH-met', 0),
('Mustafa', 'Turkish', 'Arabic', 'The chosen one', 'MOOS-ta-fa', 0),
('Ali', 'Turkish', 'Arabic', 'Sublime, exalted', 'Ah-LEE', 0),
('Hasan', 'Turkish', 'Arabic', 'Handsome, good', 'HAH-san', 0),
('Hüseyin', 'Turkish', 'Arabic', 'Beautiful, good', 'Hoo-sey-IN', 0),
('Emre', 'Turkish', 'Turkish', 'Friend, poet', 'Em-REH', 0),
('Burak', 'Turkish', 'Arabic', 'Lightning, flash', 'Boo-RAHK', 0),
('Can', 'Turkish', 'Turkish', 'Life, soul', 'Jahn', 0),
('Deniz', 'Turkish', 'Turkish', 'Sea', 'Deh-NEEZ', 0),
('Kaan', 'Turkish', 'Turkish', 'King, ruler', 'Kahn', 0),
('Ozan', 'Turkish', 'Turkish', 'Bard, storyteller', 'Oh-ZAHN', 0),
('Arda', 'Turkish', 'Turkish', 'Royal mark', 'Ahr-DAH', 0),
('Mert', 'Turkish', 'Turkish', 'Brave, authentic', 'Mehr-RT', 0),
('Efe', 'Turkish', 'Turkish', 'Brave, older brother', 'Eh-FEH', 0),
('Tuna', 'Turkish', 'Turkish', 'Danube river', 'Too-NAH', 0),
('Barış', 'Turkish', 'Turkish', 'Peace, tranquility', 'Bah-RISH', 0),
('Cem', 'Turkish', 'Turkish', 'Gathering, assembly', 'Jem', 0),
('Demir', 'Turkish', 'Turkish', 'Iron', 'Deh-MIR', 0),
('Kerem', 'Turkish', 'Turkish', 'Generosity', 'Keh-REM', 0),
('Hakan', 'Turkish', 'Turkish', 'Emperor, ruler', 'HAH-kan', 0),
('Yusuf', 'Turkish', 'Hebrew', 'God increases', 'Yoo-SOOF', 0),
('Eren', 'Turkish', 'Turkish', 'Saint, holy person', 'Eh-REN', 0),
('Süleyman', 'Turkish', 'Hebrew', 'Man of peace', 'Soo-ley-MAN', 0),
('Onur', 'Turkish', 'Turkish', 'Honor', 'Oh-NUR', 0),
('Alp', 'Turkish', 'Turkish', 'Hero, brave', 'Ahlp', 0),

-- INTERNATIONAL NAMES (25 names)
('Adrian', 'International', 'Latin', 'From Hadria', 'AY-dree-an', 10),
('Nico', 'International', 'Greek', 'Victory of the people', 'NEE-koh', 10),
('Adam', 'International', 'Hebrew/Arabic/Turkish', 'Man of the earth', 'A-dam', 10),
('Kai', 'International', 'Hawaiian/Various', 'Sea', 'KAH-ee', 10),
('Ezra', 'International', 'Hebrew', 'Help', 'EZ-ra', 10),
('Felix', 'International', 'Latin', 'Lucky, successful', 'FEE-liks', 10),
('Milan', 'International', 'Slavic', 'Gracious, dear', 'MEE-lan', 10),
('Omar', 'International', 'Arabic', 'Eloquent speaker', 'OH-mahr', 10),
('Emil', 'International', 'Latin', 'Rival', 'EH-mil', 10),
('Ivan', 'International', 'Slavic', 'God is gracious', 'EE-van', 10),
('Luca', 'International', 'Italian', 'Bringer of light', 'LOO-ka', 10),
('Max', 'International', 'Latin', 'Greatest', 'Maks', 10),
('Nael', 'International', 'Arabic/Irish', 'To achieve', 'Nye-EL', 10),
('Oscar', 'International', 'Norse', 'God spear', 'OS-kar', 10),
('Owen', 'International', 'Welsh', 'Noble, well-born', 'OH-wen', 10),
('Axel', 'International', 'Scandinavian', 'Father of peace', 'AK-sel', 10),
('Theo', 'International', 'Greek', 'Divine gift', 'THEE-oh', 10),
('Rafael', 'International', 'Hebrew', 'God has healed', 'RAH-fa-el', 10),
('Zane', 'International', 'Hebrew', 'Gift of God', 'Zayn', 10),
('Caleb', 'International', 'Hebrew', 'Faithful', 'KAY-leb', 10),
('Milo', 'International', 'German/Latin', 'Soldier', 'MY-loh', 10),
('Ellis', 'International', 'Welsh/Greek', 'Benevolent', 'EL-is', 10),
('Jonas', 'International', 'Hebrew/Greek', 'Dove', 'JOH-nas', 10),
('Victor', 'International', 'Latin', 'Conqueror', 'VIK-tor', 10),
('Leo', 'International', 'Latin', 'Lion', 'LEE-oh', 10);
